{
 "title": "Infrastructure / Prometheus",
 "tags": [
  "infrastructure",
  "kube-prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "KUBE_CLUSTER",
    "label": "Cluster",
    "query": {
     "query": "label_values(prometheus_ready,kube_cluster)"
    }
   },
   {
    "name": "PROM_INSTANCE",
    "label": "Instance",
    "query": {
     "query": "label_values(prometheus_ready{kube_cluster=~\"$KUBE_CLUSTER\"},prometheus_instance)"
    }
   },
   {
    "name": "PROM_POD",
    "label": "Prometheus Pod Name",
    "query": {
     "query": "label_values(prometheus_ready{kube_cluster=\"$KUBE_CLUSTER\", prometheus_instance=\"$PROM_INSTANCE\"},pod)"
    }
   },
   {
    "name": "PROM_JOB",
    "label": "Scrape Job",
    "query": {
     "query": "label_values({kube_cluster=\"$KUBE_CLUSTER\", prometheus_instance=\"$PROM_INSTANCE\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 } },
  { "title": "Storage", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 6, "y": 0 } },
  { "title": "Overview", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 } },
  {
   "type": "stat",
   "description": "Scraping health indicated sample quality degradation due to scraping target errors.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (prometheus_target_scrapes_exceeded_body_size_limit_total{kube_cluster=\"$KUBE_CLUSTER\",prometheus_instance=\"$PROM_INSTANCE\"}[1m])+\r\nrate (prometheus_target_scrapes_exceeded_sample_limit_total{kube_cluster=\"$KUBE_CLUSTER\",prometheus_instance=\"$PROM_INSTANCE\"}[1m])+\r\nrate (prometheus_target_scrapes_sample_duplicate_timestamp_total{kube_cluster=\"$KUBE_CLUSTER\",prometheus_instance=\"$PROM_INSTANCE\"}[1m])+\r\nrate (prometheus_target_scrapes_sample_out_of_bounds_total{kube_cluster=\"$KUBE_CLUSTER\",prometheus_instance=\"$PROM_INSTANCE\"}[1m])+\r\nrate (prometheus_target_scrapes_sample_out_of_order_total{kube_cluster=\"$KUBE_CLUSTER\",prometheus_instance=\"$PROM_INSTANCE\"}[1m]))",
     "legendFormat": "Scraping"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (scrape_duration_seconds{kube_cluster=\"$KUBE_CLUSTER\",prometheus_instance=\"$PROM_INSTANCE\"})",
     "legendFormat": "Targets"
    }
   ]
  },
  {
   "title": "Max Volume Usage",
   "type": "gauge",
   "description": "Maximum volume usage of the bounded data volumes.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (max by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{kube_cluster=\"$KUBE_CLUSTER\",persistentvolumeclaim=~\".*$PROM_POD\"}/kubelet_volume_stats_capacity_bytes{kube_cluster=\"$KUBE_CLUSTER\",persistentvolumeclaim=~\".*$PROM_POD\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Storage Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (max by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{kube_cluster=\"$KUBE_CLUSTER\",persistentvolumeclaim=~\".*$PROM_POD\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "stat",
   "description": "Total number of targets scraped.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (prometheus_sd_discovered_targets{kube_cluster=\"$KUBE_CLUSTER\",prometheus_instance=\"$PROM_INSTANCE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active series",
   "type": "stat",
   "description": "Total number of series active in prometheus TSDB head chunks. (updated within last 2 hours)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{kube_cluster=\"$KUBE_CLUSTER\",prometheus_instance=\"$PROM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max target latency",
   "type": "stat",
   "description": "Maximum duration for scraping the targets.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (scrape_duration_seconds{kube_cluster=\"$KUBE_CLUSTER\",prometheus_instance=\"$PROM_INSTANCE\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Ingestion speed",
   "type": "stat",
   "description": "Speed new samples are scraped and ingested.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate (prometheus_tsdb_head_samples_appended_total{kube_cluster=\"$KUBE_CLUSTER\",prometheus_instance=\"$PROM_INSTANCE\",type=\"float\"}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    { "title": "Job name", "type": "text", "gridPos": { "h": 1, "w": 5, "x": 0, "y": 7 } },
    { "title": "Targets", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 5, "y": 7 } },
    { "title": "Endpoints", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 7, "y": 7 } },
    { "title": "Uptime", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 9, "y": 7 } },
    { "title": "Sync duration", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 12, "y": 7 } },
    { "title": "Series", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 15, "y": 7 } },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 8 },
     "repeat": "PROM_JOB",
     "options": {
      "content": "<div style=\"height: 100%; width: 100%; border: 0px solid black; display: flex; justify-content: center; align-items: center;\">\n  <p style=\"font-weight: bold; margin: 0;\">$PROM_JOB</p>\n</div>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 5, "y": 8 },
     "repeat": "PROM_JOB",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (count by (instance) (scrape_duration_seconds{kube_cluster=\"$KUBE_CLUSTER\", prometheus_instance=\"$PROM_INSTANCE\", job=\"$PROM_JOB\"}))",
       "legendFormat": "Targets"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 7, "y": 8 },
     "repeat": "PROM_JOB",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (scrape_duration_seconds{kube_cluster=\"$KUBE_CLUSTER\", prometheus_instance=\"$PROM_INSTANCE\", job=\"$PROM_JOB\"})",
       "legendFormat": "Targets"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 8 },
     "repeat": "PROM_JOB",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max (time() - process_start_time_seconds{kube_cluster=\"$KUBE_CLUSTER\", prometheus_instance=\"$PROM_INSTANCE\", job=\"$PROM_JOB\"})",
       "legendFormat": "Uptime"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 8 },
     "repeat": "PROM_JOB",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg (scrape_duration_seconds{kube_cluster=\"$KUBE_CLUSTER\", prometheus_instance=\"$PROM_INSTANCE\", job=\"$PROM_JOB\"})",
       "legendFormat": "Scrape Duration"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 8 },
     "repeat": "PROM_JOB",
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count ({__name__=~\".*\", job=\"$PROM_JOB\", kube_cluster=\"$KUBE_CLUSTER\", prometheus_instance=\"$PROM_INSTANCE\"})",
       "legendFormat": "Series"
      }
     ]
    }
   ]
  },
  {
   "title": "Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Stats",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (kube_cluster, job, instance, version) (prometheus_build_info{kube_cluster=~\"$KUBE_CLUSTER\", prometheus_instance=~\"$PROM_INSTANCE\"})"
      }
     ]
    }
   ]
  }
 ]
}