---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "77.12.0"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    grafana:
      defaultDashboardsTimezone: "Asia/Shanghai"
      adminUser: admin
      adminPassword: "OPERATOR-password123A"
    prometheus:
      prometheusSpec:
        retention: 32d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: juicefs
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 1024Gi