---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-agent
  namespace: gitlab-agent
spec:
  targetNamespace: gitlab-agent
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/k3s-prod-0/gitlab-agent
  prune: true
  commonMetadata:
    labels:
      zty89.com/managed-by: flux