---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-agent
  labels:
    zty89.com/managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: juicefs
  labels:
    zty89.com/managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-prometheus
  labels:
    zty89.com/managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    zty89.com/managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    zty89.com/managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    zty89.com/managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: nats
  labels:
    zty89.com/managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    zty89.com/managed-by: flux