---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: juicefs-sc
  namespace: juicefs
spec:
  dependsOn:
    - name: secrets
      namespace: flux-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./storage-classes/k3s-prod-0/juicefs
  prune: true
  commonMetadata:
    labels:
      zty89.com/managed-by: flux