---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.26.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg-helm-repo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 1000m
        memory: 200Mi
    monitoring:
      podMonitorEnabled: true
      podMonitorAdditionalLabels:
        zty89.com/prometheus: default-prometheus
      grafanaDashboard:
        create: true
        namespace: "kube-prometheus"
        labels:
          zty89.com/grafana-dashboard: "1"