---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: juicefs-csi-driver
  namespace: juicefs
spec:
  targetNamespace: juicefs
  interval: 1h
  chart:
    spec:
      chart: juicefs-csi-driver
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: juicefs-csi-driver
        namespace: flux-system
  values:
    controller:
      labels:
        zty89.com/managed-by: flux
    node:
      labels:
        zty89.com/managed-by: flux
    dashboard:
      labels:
        zty89.com/managed-by: flux
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3