---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: juicefs-csi-driver
  namespace: juicefs
spec:
  interval: 10m
  chart:
    spec:
      chart: juicefs-csi-driver
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: juicefs-csi-driver
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 512Mi
    node:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 512Mi
    dashboard:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 1000m
          memory: 512Mi
    globalConfig:
      mountPodPatch:
        - resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          mountOptions:
            - backup-meta=86400
            - backup-skip-trash
            - cache-size=50G
    storageClasses:
      - name: "juicefs-0"
        enabled: true
        existingSecret: "juicefs-0-secret"
        reclaimPolicy: Retain
        allowVolumeExpansion: true