---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: juicefs-csi-driver
  namespace: juicefs
spec:
  interval: 10m
  chart:
    spec:
      chart: juicefs-csi-driver
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: juicefs-csi-driver
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
    node:
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 200Mi
    dashboard:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 1000m
          memory: 200Mi
    globalConfig:
      mountPodPatch:
        - resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          mountOptions:
            - backup-meta=86400
            - backup-skip-trash
            - cache-size=50G
        - pvcSelector:
            matchLabels:
              zty89.com/env: "database"
          mountOptions:
            - backup-meta=86400
            - backup-skip-trash
            - cache-size=50G
            - writeback_cache
            - writeback
            - buffer-size=1G
            - prefetch=0
            - max-readahead=0
    storageClasses:
      - name: "juicefs-0"
        enabled: true
        existingSecret: "juicefs-0-secret"
        reclaimPolicy: Retain
        allowVolumeExpansion: true