---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: juicefs-csi-driver
  namespace: juicefs
spec:
  interval: 1h
  chart:
    spec:
      chart: juicefs-csi-driver
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: juicefs-csi-driver
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    storageClasses:
      - name: "juicefs-0"
        enabled: true
        existingSecret: "juicefs-0-secret"
        reclaimPolicy: Retain
        allowVolumeExpansion: true
        mountPod:
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 4000m
              memory: 4Gi