---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: primary
  namespace: nats
spec:
  interval: 15m
  chart:
    spec:
      chart: nats
      version: "v1.3.15"
      sourceRef:
        kind: HelmRepository
        name: nats-helm-repo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    tlsCA:
      enabled: true
      secretName: nats-server-tls
    config:
      cluster:
        enabled: true
        replicas: 3
        tls:
          enabled: true
          secretName: nats-server-tls
      jetstream:
        enabled: true
        fileStore:
          enabled: true
          pvc:
            enabled: true
            size: 200Gi
            storageClassName: iscsi
        memoryStore:
          enabled: true
          size: 2Gi
      nats:
        tls:
          enabled: true
          secretName: nats-server-tls
      monitor:
        enabled: true
      resolver:
        enabled: true
        pvc:
          enabled: true
          size: 1Gi
          storageClassName: iscsi
      merge:
        operator: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJPSFRQVlVBVTNQT1RFNzJKTlhONUFYU1JaVTJMQzdXTDNZUVRKSTNYUFZCUElaNk5BWDZBIiwiaWF0IjoxNzYxMjk2MjA2LCJpc3MiOiJPQk5QRU9LWUlHQjZQNldZT1FQWjJSUFlVWlY2RkxWWTNPTVNSVzJXUUNDRTI3VUlTNEpYRVQ2RyIsIm5hbWUiOiJvcCIsInN1YiI6Ik9CTlBFT0tZSUdCNlA2V1lPUVBaMlJQWVVaVjZGTFZZM09NU1JXMldRQ0NFMjdVSVM0SlhFVDZHIiwibmF0cyI6eyJzeXN0ZW1fYWNjb3VudCI6IkFDSk9MVUFXNVUzR1VLNlk1QkJKTFZRUDNKVFdIQ1k3SzZEWUVPQjRBTVAzUzI0WFZNUDVVUjVCIiwidHlwZSI6Im9wZXJhdG9yIiwidmVyc2lvbiI6Mn19.t1nu0GrlRETrqifVIF6E7xvfb7LdWilAwlhSvIgqpWvlEOgUPS0AdKpmAkRrkYIHodpURlju-VfPhhRDoI0VAA
        system_account: ACJOLUAW5U3GUK6Y5BBJLVQP3JTWHCY7K6DYEOB4AMP3S24XVMP5UR5B
        resolver:
          type: full
          allow_delete: true
          interval: 2m
          timeout: 1.9s
        resolver_preload:
          ACJOLUAW5U3GUK6Y5BBJLVQP3JTWHCY7K6DYEOB4AMP3S24XVMP5UR5B: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJNWDY3MzdMQUxMNFRDNkpERDZNWEVUNldVSjNFRkNBMllIWE1VWkQzR01YQlhVTVJUNU1RIiwiaWF0IjoxNzYxMjk2MjA2LCJpc3MiOiJPQk5QRU9LWUlHQjZQNldZT1FQWjJSUFlVWlY2RkxWWTNPTVNSVzJXUUNDRTI3VUlTNEpYRVQ2RyIsIm5hbWUiOiJTWVMiLCJzdWIiOiJBQ0pPTFVBVzVVM0dVSzZZNUJCSkxWUVAzSlRXSENZN0s2RFlFT0I0QU1QM1MyNFhWTVA1VVI1QiIsIm5hdHMiOnsiZXhwb3J0cyI6W3sibmFtZSI6ImFjY291bnQtbW9uaXRvcmluZy1zdHJlYW1zIiwic3ViamVjdCI6IiRTWVMuQUNDT1VOVC4qLlx1MDAzZSIsInR5cGUiOiJzdHJlYW0iLCJhY2NvdW50X3Rva2VuX3Bvc2l0aW9uIjozLCJkZXNjcmlwdGlvbiI6IkFjY291bnQgc3BlY2lmaWMgbW9uaXRvcmluZyBzdHJlYW0iLCJpbmZvX3VybCI6Imh0dHBzOi8vZG9jcy5uYXRzLmlvL25hdHMtc2VydmVyL2NvbmZpZ3VyYXRpb24vc3lzX2FjY291bnRzIn0seyJuYW1lIjoiYWNjb3VudC1tb25pdG9yaW5nLXNlcnZpY2VzIiwic3ViamVjdCI6IiRTWVMuUkVRLkFDQ09VTlQuKi4qIiwidHlwZSI6InNlcnZpY2UiLCJyZXNwb25zZV90eXBlIjoiU3RyZWFtIiwiYWNjb3VudF90b2tlbl9wb3NpdGlvbiI6NCwiZGVzY3JpcHRpb24iOiJSZXF1ZXN0IGFjY291bnQgc3BlY2lmaWMgbW9uaXRvcmluZyBzZXJ2aWNlcyBmb3I6IFNVQlNaLCBDT05OWiwgTEVBRlosIEpTWiBhbmQgSU5GTyIsImluZm9fdXJsIjoiaHR0cHM6Ly9kb2NzLm5hdHMuaW8vbmF0cy1zZXJ2ZXIvY29uZmlndXJhdGlvbi9zeXNfYWNjb3VudHMifV0sImxpbWl0cyI6eyJzdWJzIjotMSwiZGF0YSI6LTEsInBheWxvYWQiOi0xLCJpbXBvcnRzIjotMSwiZXhwb3J0cyI6LTEsIndpbGRjYXJkcyI6dHJ1ZSwiY29ubiI6LTEsImxlYWYiOi0xfSwic2lnbmluZ19rZXlzIjpbIkFDWTUyMzNITE1QRDVaNUNOQkJKV0Q3WkVQSkI1SUNUSEFONlVVVklEQ1BNMlUzRzIzNTdaVVRIIl0sImRlZmF1bHRfcGVybWlzc2lvbnMiOnsicHViIjp7fSwic3ViIjp7fX0sImF1dGhvcml6YXRpb24iOnt9LCJ0eXBlIjoiYWNjb3VudCIsInZlcnNpb24iOjJ9fQ.kYKPthjTSd8GW_ZQIkby_mDmFzuXbJkTSEpfIWtCk73CtuapezXcWtgofCPlY2Vf3xjUMsJ87qQmW3U064PeCQ
    promExporter:
      enabled: true
      podMonitor:
        enabled: true
        merge:
          metadata:
            labels:
              zty89.com/prometheus: default-prometheus
    natsBox:
      enabled: false