---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
  namespace: nats
spec:
  interval: 15m
  chart:
    spec:
      chart: nats
      version: "v1.3.15"
      sourceRef:
        kind: HelmRepository
        name: nats-helm-repo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: shanghai0
    tlsCA:
      enabled: true
      secretName: nats-server-tls
    config:
      cluster:
        enabled: true
        replicas: 3
        tls:
          enabled: true
          secretName: nats-server-tls
      jetstream:
        enabled: true
        fileStore:
          enabled: true
          pvc:
            enabled: true
            size: 200Gi
            storageClassName: iscsi
        memoryStore:
          enabled: true
          size: 2Gi
      nats:
        tls:
          enabled: true
          secretName: nats-server-tls
      monitor:
        enabled: true
      resolver:
        enabled: true
        pvc:
          enabled: true
          size: 1Gi
          storageClassName: iscsi
      merge:
        operator: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJKMlRTTkRYUUZOTllTREwyNkJYU1VYQVJYN1lZWFAzNUZaV0hHUE5aTE5MSjJVNFBJSEJBIiwiaWF0IjoxNzYxMjgyODI2LCJpc3MiOiJPQU9RWE9QQUY0WVNFUUFVQ0JDR0dDQldKNkM0UFRZTTRXRVZHRjNKNlREUUlDREhJSFZBUlBSSyIsIm5hbWUiOiJvcC10eXpob3UiLCJzdWIiOiJPQU9RWE9QQUY0WVNFUUFVQ0JDR0dDQldKNkM0UFRZTTRXRVZHRjNKNlREUUlDREhJSFZBUlBSSyIsIm5hdHMiOnsib3BlcmF0b3Jfc2VydmljZV91cmxzIjpbIm5hdHM6Ly9sb2NhbGhvc3Q6NDIyMiJdLCJzeXN0ZW1fYWNjb3VudCI6IkFBVUZCNVU2VDZCNkxaNlpET043VlNOWTdHWFdZRk83QkVQSjZLVUhUR003WVZIMlpHR1ZQRlJWIiwidHlwZSI6Im9wZXJhdG9yIiwidmVyc2lvbiI6Mn19.l1aCjyZEiWRO5yIkNIHxRst_eSR097MmHWMOWN0lDaAVl-VtGyglqgov0awajbBxuWbnUP_Q6a9tMD3DuHdaDA
        system_account: AAUFB5U6T6B6LZ6ZDON7VSNY7GXWYFO7BEPJ6KUHTGM7YVH2ZGGVPFRV
        resolver:
          type: full
          allow_delete: true
          interval: 2m
          timeout: 1.9s
        resolver_preload:
          AAUFB5U6T6B6LZ6ZDON7VSNY7GXWYFO7BEPJ6KUHTGM7YVH2ZGGVPFRV: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJLRFE3UkpMTVJTVVBDVkNBN0g3REIySUZaR1FXS0ZPVUJOQVJGTkE3RVNaVTZMTUlETkRRIiwiaWF0IjoxNzYxMjgyODI2LCJpc3MiOiJPQU9RWE9QQUY0WVNFUUFVQ0JDR0dDQldKNkM0UFRZTTRXRVZHRjNKNlREUUlDREhJSFZBUlBSSyIsIm5hbWUiOiJTWVMiLCJzdWIiOiJBQVVGQjVVNlQ2QjZMWjZaRE9ON1ZTTlk3R1hXWUZPN0JFUEo2S1VIVEdNN1lWSDJaR0dWUEZSViIsIm5hdHMiOnsiZXhwb3J0cyI6W3sibmFtZSI6ImFjY291bnQtbW9uaXRvcmluZy1zdHJlYW1zIiwic3ViamVjdCI6IiRTWVMuQUNDT1VOVC4qLlx1MDAzZSIsInR5cGUiOiJzdHJlYW0iLCJhY2NvdW50X3Rva2VuX3Bvc2l0aW9uIjozLCJkZXNjcmlwdGlvbiI6IkFjY291bnQgc3BlY2lmaWMgbW9uaXRvcmluZyBzdHJlYW0iLCJpbmZvX3VybCI6Imh0dHBzOi8vZG9jcy5uYXRzLmlvL25hdHMtc2VydmVyL2NvbmZpZ3VyYXRpb24vc3lzX2FjY291bnRzIn0seyJuYW1lIjoiYWNjb3VudC1tb25pdG9yaW5nLXNlcnZpY2VzIiwic3ViamVjdCI6IiRTWVMuUkVRLkFDQ09VTlQuKi4qIiwidHlwZSI6InNlcnZpY2UiLCJyZXNwb25zZV90eXBlIjoiU3RyZWFtIiwiYWNjb3VudF90b2tlbl9wb3NpdGlvbiI6NCwiZGVzY3JpcHRpb24iOiJSZXF1ZXN0IGFjY291bnQgc3BlY2lmaWMgbW9uaXRvcmluZyBzZXJ2aWNlcyBmb3I6IFNVQlNaLCBDT05OWiwgTEVBRlosIEpTWiBhbmQgSU5GTyIsImluZm9fdXJsIjoiaHR0cHM6Ly9kb2NzLm5hdHMuaW8vbmF0cy1zZXJ2ZXIvY29uZmlndXJhdGlvbi9zeXNfYWNjb3VudHMifV0sImxpbWl0cyI6eyJzdWJzIjotMSwiZGF0YSI6LTEsInBheWxvYWQiOi0xLCJpbXBvcnRzIjotMSwiZXhwb3J0cyI6LTEsIndpbGRjYXJkcyI6dHJ1ZSwiY29ubiI6LTEsImxlYWYiOi0xfSwic2lnbmluZ19rZXlzIjpbIkFCSlVRRUVPV0VMM0c1QzJBQzVIWlg3WldRQ0hWSFE0UDc2RkZITDZXU0VHSVVVU0w1SlJJSUlFIl0sImRlZmF1bHRfcGVybWlzc2lvbnMiOnsicHViIjp7fSwic3ViIjp7fX0sImF1dGhvcml6YXRpb24iOnt9LCJ0eXBlIjoiYWNjb3VudCIsInZlcnNpb24iOjJ9fQ.yJeiPu7M42dQ5LrujUJXKMJxsfJg4rLobgeJh9gDCdyNoTgfltfC7eRkJ1B8bGPbh0_2GeIL16KpeUOtbzd8CQ
    promExporter:
      enabled: true
      podMonitor:
        enabled: true
        merge:
          metadata:
            labels:
              zty89.com/prometheus: default-prometheus